export const LANGUAGE_OPTIONS = [
    { code: 'en', label: 'English' },
    { code: 'ru', label: 'Русский' },
    { code: 'es', label: 'Español' },
    { code: 'fr', label: 'Français' },
    { code: 'de', label: 'Deutsch' },
    { code: 'it', label: 'Italiano' },
    { code: 'pt', label: 'Português' },
    { code: 'zh', label: '中文' },
    { code: 'ja', label: '日本語' },
    { code: 'ko', label: '한국어' },
    { code: 'ar', label: 'العربية' },
    { code: 'hi', label: 'हिन्दी' },
    { code: 'tr', label: 'Türkçe' },
    { code: 'pl', label: 'Polski' },
    { code: 'nl', label: 'Nederlands' },
    { code: 'sv', label: 'Svenska' },
    { code: 'da', label: 'Dansk' },
    { code: 'no', label: 'Norsk' },
    { code: 'fi', label: 'Suomi' },
    { code: 'cs', label: 'Čeština' },
    { code: 'sk', label: 'Slovenčina' },
    { code: 'hu', label: 'Magyar' },
    { code: 'ro', label: 'Română' },
    { code: 'bg', label: 'Български' },
    { code: 'hr', label: 'Hrvatski' },
    { code: 'sr', label: 'Српски' },
    { code: 'sl', label: 'Slovenščina' },
    { code: 'et', label: 'Eesti' },
    { code: 'lv', label: 'Latviešu' },
    { code: 'lt', label: 'Lietuvių' },
    { code: 'el', label: 'Ελληνικά' },
    { code: 'he', label: 'עברית' },
    { code: 'th', label: 'ไทย' },
    { code: 'vi', label: 'Tiếng Việt' },
    { code: 'id', label: 'Bahasa Indonesia' },
    { code: 'ms', label: 'Bahasa Melayu' },
    { code: 'tl', label: 'Filipino' },
    { code: 'sw', label: 'Kiswahili' },
    { code: 'zu', label: 'isiZulu' },
    { code: 'af', label: 'Afrikaans' },
    { code: 'am', label: 'አማርኛ' },
    { code: 'bn', label: 'বাংলা' },
    { code: 'gu', label: 'ગુજરાતી' },
    { code: 'kn', label: 'ಕನ್ನಡ' },
    { code: 'ml', label: 'മലയാളം' },
    { code: 'mr', label: 'मराठी' },
    { code: 'pa', label: 'ਪੰਜਾਬੀ' },
    { code: 'ta', label: 'தமிழ்' },
    { code: 'te', label: 'తెలుగు' },
    { code: 'ur', label: 'اردو' },
    { code: 'fa', label: 'فارسی' },
    { code: 'ps', label: 'پښتو' },
    { code: 'ky', label: 'Кыргызча' },
    { code: 'kk', label: 'Қазақша' },
    { code: 'uz', label: "O'zbekcha" },
    { code: 'tg', label: 'Тоҷикӣ' },
    { code: 'mn', label: 'Монгол' },
    { code: 'my', label: 'မြန်မာ' },
    { code: 'km', label: 'ខ្មែរ' },
    { code: 'lo', label: 'ລາວ' },
    { code: 'si', label: 'සිංහල' },
    { code: 'ne', label: 'नेपाली' },
    { code: 'dz', label: 'རྫོང་ཁ' },
    { code: 'bo', label: 'བོད་སྐད་' }
];

const LANGUAGE_NAME_MAP = LANGUAGE_OPTIONS.reduce((acc, { code, label }) => {
    acc[code] = label;
    return acc;
}, {});

export function getLanguageLabel(code) {
    return LANGUAGE_NAME_MAP[code] || code;
}

